tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "hashicorp/tap"
brew "hashicorp/tap/terraform"
brew "hashicorp/tap/packer"
cask "vagrant"
brew "vagrant-completion"
cask "vagrant-manager"

